// <auto-generated />
using System;
using FamilyBudget.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamilyBudget.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200112145521_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FamilyBudget.Domain.Entities.FinancialPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FinancialPeriods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 1, 12, 14, 55, 10, 429, DateTimeKind.Utc).AddTicks(249),
                            Modified = new DateTime(2020, 1, 12, 14, 55, 10, 429, DateTimeKind.Utc).AddTicks(262),
                            Name = "First",
                            PeriodBegin = new DateTime(2020, 1, 12, 14, 55, 10, 429, DateTimeKind.Utc).AddTicks(263),
                            PeriodEnd = new DateTime(2020, 1, 27, 14, 55, 10, 429, DateTimeKind.Utc).AddTicks(263)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
